// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/deck/v1/deck.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Card_Suit int32

const (
	Card_SUIT_UNSPECIFIED Card_Suit = 0
	Card_SUIT_ACES        Card_Suit = 1
	Card_SUIT_SPADES      Card_Suit = 2
	Card_SUIT_DIAMONDS    Card_Suit = 3
	Card_SUIT_CLUBS       Card_Suit = 4
	Card_SUIT_JOKERS      Card_Suit = 5
)

// Enum value maps for Card_Suit.
var (
	Card_Suit_name = map[int32]string{
		0: "SUIT_UNSPECIFIED",
		1: "SUIT_ACES",
		2: "SUIT_SPADES",
		3: "SUIT_DIAMONDS",
		4: "SUIT_CLUBS",
		5: "SUIT_JOKERS",
	}
	Card_Suit_value = map[string]int32{
		"SUIT_UNSPECIFIED": 0,
		"SUIT_ACES":        1,
		"SUIT_SPADES":      2,
		"SUIT_DIAMONDS":    3,
		"SUIT_CLUBS":       4,
		"SUIT_JOKERS":      5,
	}
)

func (x Card_Suit) Enum() *Card_Suit {
	p := new(Card_Suit)
	*p = x
	return p
}

func (x Card_Suit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Card_Suit) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_deck_v1_deck_proto_enumTypes[0].Descriptor()
}

func (Card_Suit) Type() protoreflect.EnumType {
	return &file_proto_deck_v1_deck_proto_enumTypes[0]
}

func (x Card_Suit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Card_Suit.Descriptor instead.
func (Card_Suit) EnumDescriptor() ([]byte, []int) {
	return file_proto_deck_v1_deck_proto_rawDescGZIP(), []int{1, 0}
}

type Deck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deck) Reset() {
	*x = Deck{}
	mi := &file_proto_deck_v1_deck_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deck) ProtoMessage() {}

func (x *Deck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_v1_deck_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deck.ProtoReflect.Descriptor instead.
func (*Deck) Descriptor() ([]byte, []int) {
	return file_proto_deck_v1_deck_proto_rawDescGZIP(), []int{0}
}

func (x *Deck) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suit          Card_Suit              `protobuf:"varint,1,opt,name=suit,proto3,enum=deck.v1.deck.Card_Suit" json:"suit,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_proto_deck_v1_deck_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_v1_deck_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_proto_deck_v1_deck_proto_rawDescGZIP(), []int{1}
}

func (x *Card) GetSuit() Card_Suit {
	if x != nil {
		return x.Suit
	}
	return Card_SUIT_UNSPECIFIED
}

func (x *Card) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type FetchCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deck          *Deck                  `protobuf:"bytes,1,opt,name=deck,proto3" json:"deck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchCardRequest) Reset() {
	*x = FetchCardRequest{}
	mi := &file_proto_deck_v1_deck_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCardRequest) ProtoMessage() {}

func (x *FetchCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_v1_deck_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCardRequest.ProtoReflect.Descriptor instead.
func (*FetchCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_deck_v1_deck_proto_rawDescGZIP(), []int{2}
}

func (x *FetchCardRequest) GetDeck() *Deck {
	if x != nil {
		return x.Deck
	}
	return nil
}

type PushCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deck          *Deck                  `protobuf:"bytes,1,opt,name=deck,proto3" json:"deck,omitempty"`
	Card          *Card                  `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushCardRequest) Reset() {
	*x = PushCardRequest{}
	mi := &file_proto_deck_v1_deck_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushCardRequest) ProtoMessage() {}

func (x *PushCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_v1_deck_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushCardRequest.ProtoReflect.Descriptor instead.
func (*PushCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_deck_v1_deck_proto_rawDescGZIP(), []int{3}
}

func (x *PushCardRequest) GetDeck() *Deck {
	if x != nil {
		return x.Deck
	}
	return nil
}

func (x *PushCardRequest) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_deck_v1_deck_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_v1_deck_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_deck_v1_deck_proto_rawDescGZIP(), []int{4}
}

var File_proto_deck_v1_deck_proto protoreflect.FileDescriptor

const file_proto_deck_v1_deck_proto_rawDesc = "" +
	"\n" +
	"\x18proto/deck/v1/deck.proto\x12\fdeck.v1.deck\"\x1f\n" +
	"\x04Deck\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\"\xbb\x01\n" +
	"\x04Card\x12+\n" +
	"\x04suit\x18\x01 \x01(\x0e2\x17.deck.v1.deck.Card.SuitR\x04suit\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"p\n" +
	"\x04Suit\x12\x14\n" +
	"\x10SUIT_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSUIT_ACES\x10\x01\x12\x0f\n" +
	"\vSUIT_SPADES\x10\x02\x12\x11\n" +
	"\rSUIT_DIAMONDS\x10\x03\x12\x0e\n" +
	"\n" +
	"SUIT_CLUBS\x10\x04\x12\x0f\n" +
	"\vSUIT_JOKERS\x10\x05\":\n" +
	"\x10FetchCardRequest\x12&\n" +
	"\x04deck\x18\x01 \x01(\v2\x12.deck.v1.deck.DeckR\x04deck\"a\n" +
	"\x0fPushCardRequest\x12&\n" +
	"\x04deck\x18\x01 \x01(\v2\x12.deck.v1.deck.DeckR\x04deck\x12&\n" +
	"\x04card\x18\x02 \x01(\v2\x12.deck.v1.deck.CardR\x04card\"\a\n" +
	"\x05Empty2\xc7\x01\n" +
	"\vDeckService\x123\n" +
	"\x06Create\x12\x13.deck.v1.deck.Empty\x1a\x12.deck.v1.deck.Deck\"\x00\x12A\n" +
	"\tFetchCard\x12\x1e.deck.v1.deck.FetchCardRequest\x1a\x12.deck.v1.deck.Card\"\x00\x12@\n" +
	"\bPushCard\x12\x1d.deck.v1.deck.PushCardRequest\x1a\x13.deck.v1.deck.Empty\"\x00B\x98\x01\n" +
	"\x10com.deck.v1.deckB\tDeckProtoP\x01Z'github.com/chn555/schemas/proto/deck/v1\xa2\x02\x03DVD\xaa\x02\fDeck.V1.Deck\xca\x02\fDeck\\V1\\Deck\xe2\x02\x18Deck\\V1\\Deck\\GPBMetadata\xea\x02\x0eDeck::V1::Deckb\x06proto3"

var (
	file_proto_deck_v1_deck_proto_rawDescOnce sync.Once
	file_proto_deck_v1_deck_proto_rawDescData []byte
)

func file_proto_deck_v1_deck_proto_rawDescGZIP() []byte {
	file_proto_deck_v1_deck_proto_rawDescOnce.Do(func() {
		file_proto_deck_v1_deck_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_deck_v1_deck_proto_rawDesc), len(file_proto_deck_v1_deck_proto_rawDesc)))
	})
	return file_proto_deck_v1_deck_proto_rawDescData
}

var file_proto_deck_v1_deck_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_deck_v1_deck_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_deck_v1_deck_proto_goTypes = []any{
	(Card_Suit)(0),           // 0: deck.v1.deck.Card.Suit
	(*Deck)(nil),             // 1: deck.v1.deck.Deck
	(*Card)(nil),             // 2: deck.v1.deck.Card
	(*FetchCardRequest)(nil), // 3: deck.v1.deck.FetchCardRequest
	(*PushCardRequest)(nil),  // 4: deck.v1.deck.PushCardRequest
	(*Empty)(nil),            // 5: deck.v1.deck.Empty
}
var file_proto_deck_v1_deck_proto_depIdxs = []int32{
	0, // 0: deck.v1.deck.Card.suit:type_name -> deck.v1.deck.Card.Suit
	1, // 1: deck.v1.deck.FetchCardRequest.deck:type_name -> deck.v1.deck.Deck
	1, // 2: deck.v1.deck.PushCardRequest.deck:type_name -> deck.v1.deck.Deck
	2, // 3: deck.v1.deck.PushCardRequest.card:type_name -> deck.v1.deck.Card
	5, // 4: deck.v1.deck.DeckService.Create:input_type -> deck.v1.deck.Empty
	3, // 5: deck.v1.deck.DeckService.FetchCard:input_type -> deck.v1.deck.FetchCardRequest
	4, // 6: deck.v1.deck.DeckService.PushCard:input_type -> deck.v1.deck.PushCardRequest
	1, // 7: deck.v1.deck.DeckService.Create:output_type -> deck.v1.deck.Deck
	2, // 8: deck.v1.deck.DeckService.FetchCard:output_type -> deck.v1.deck.Card
	5, // 9: deck.v1.deck.DeckService.PushCard:output_type -> deck.v1.deck.Empty
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_deck_v1_deck_proto_init() }
func file_proto_deck_v1_deck_proto_init() {
	if File_proto_deck_v1_deck_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_deck_v1_deck_proto_rawDesc), len(file_proto_deck_v1_deck_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_deck_v1_deck_proto_goTypes,
		DependencyIndexes: file_proto_deck_v1_deck_proto_depIdxs,
		EnumInfos:         file_proto_deck_v1_deck_proto_enumTypes,
		MessageInfos:      file_proto_deck_v1_deck_proto_msgTypes,
	}.Build()
	File_proto_deck_v1_deck_proto = out.File
	file_proto_deck_v1_deck_proto_goTypes = nil
	file_proto_deck_v1_deck_proto_depIdxs = nil
}
