// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/blackjack/v1/blackjack.proto

package v1

import (
	v1 "github.com/chn555/schemas/proto/deck/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Game_GAME_STATUS int32

const (
	Game_GAME_STATUS_UNSPECIFIED         Game_GAME_STATUS = 0
	Game_GAME_STATUS_WAITING_FOR_PLAYERS Game_GAME_STATUS = 1
	Game_GAME_STATUS_FINISHED            Game_GAME_STATUS = 2
)

// Enum value maps for Game_GAME_STATUS.
var (
	Game_GAME_STATUS_name = map[int32]string{
		0: "GAME_STATUS_UNSPECIFIED",
		1: "GAME_STATUS_WAITING_FOR_PLAYERS",
		2: "GAME_STATUS_FINISHED",
	}
	Game_GAME_STATUS_value = map[string]int32{
		"GAME_STATUS_UNSPECIFIED":         0,
		"GAME_STATUS_WAITING_FOR_PLAYERS": 1,
		"GAME_STATUS_FINISHED":            2,
	}
)

func (x Game_GAME_STATUS) Enum() *Game_GAME_STATUS {
	p := new(Game_GAME_STATUS)
	*p = x
	return p
}

func (x Game_GAME_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Game_GAME_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_blackjack_v1_blackjack_proto_enumTypes[0].Descriptor()
}

func (Game_GAME_STATUS) Type() protoreflect.EnumType {
	return &file_proto_blackjack_v1_blackjack_proto_enumTypes[0]
}

func (x Game_GAME_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Game_GAME_STATUS.Descriptor instead.
func (Game_GAME_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_proto_blackjack_v1_blackjack_proto_rawDescGZIP(), []int{0, 0}
}

type Turn_TURN_ACTION int32

const (
	Turn_TURN_ACTION_UNSPECIFIED Turn_TURN_ACTION = 0
	Turn_TURN_ACTION_HIT         Turn_TURN_ACTION = 1
	Turn_TURN_ACTION_STAND       Turn_TURN_ACTION = 2
)

// Enum value maps for Turn_TURN_ACTION.
var (
	Turn_TURN_ACTION_name = map[int32]string{
		0: "TURN_ACTION_UNSPECIFIED",
		1: "TURN_ACTION_HIT",
		2: "TURN_ACTION_STAND",
	}
	Turn_TURN_ACTION_value = map[string]int32{
		"TURN_ACTION_UNSPECIFIED": 0,
		"TURN_ACTION_HIT":         1,
		"TURN_ACTION_STAND":       2,
	}
)

func (x Turn_TURN_ACTION) Enum() *Turn_TURN_ACTION {
	p := new(Turn_TURN_ACTION)
	*p = x
	return p
}

func (x Turn_TURN_ACTION) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Turn_TURN_ACTION) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_blackjack_v1_blackjack_proto_enumTypes[1].Descriptor()
}

func (Turn_TURN_ACTION) Type() protoreflect.EnumType {
	return &file_proto_blackjack_v1_blackjack_proto_enumTypes[1]
}

func (x Turn_TURN_ACTION) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Turn_TURN_ACTION.Descriptor instead.
func (Turn_TURN_ACTION) EnumDescriptor() ([]byte, []int) {
	return file_proto_blackjack_v1_blackjack_proto_rawDescGZIP(), []int{1, 0}
}

type Game struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GameId             string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlayerCards        []*v1.Card             `protobuf:"bytes,2,rep,name=player_cards,json=playerCards,proto3" json:"player_cards,omitempty"`
	VisibleDealerCards []*v1.Card             `protobuf:"bytes,3,rep,name=visible_dealer_cards,json=visibleDealerCards,proto3" json:"visible_dealer_cards,omitempty"`
	PlayerScore        int32                  `protobuf:"varint,4,opt,name=player_score,json=playerScore,proto3" json:"player_score,omitempty"`
	DealerScore        int32                  `protobuf:"varint,5,opt,name=dealer_score,json=dealerScore,proto3" json:"dealer_score,omitempty"`
	Status             Game_GAME_STATUS       `protobuf:"varint,6,opt,name=status,proto3,enum=blackjack.v1.blackjack.Game_GAME_STATUS" json:"status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_proto_blackjack_v1_blackjack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blackjack_v1_blackjack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_proto_blackjack_v1_blackjack_proto_rawDescGZIP(), []int{0}
}

func (x *Game) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *Game) GetPlayerCards() []*v1.Card {
	if x != nil {
		return x.PlayerCards
	}
	return nil
}

func (x *Game) GetVisibleDealerCards() []*v1.Card {
	if x != nil {
		return x.VisibleDealerCards
	}
	return nil
}

func (x *Game) GetPlayerScore() int32 {
	if x != nil {
		return x.PlayerScore
	}
	return 0
}

func (x *Game) GetDealerScore() int32 {
	if x != nil {
		return x.DealerScore
	}
	return 0
}

func (x *Game) GetStatus() Game_GAME_STATUS {
	if x != nil {
		return x.Status
	}
	return Game_GAME_STATUS_UNSPECIFIED
}

type Turn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        Turn_TURN_ACTION       `protobuf:"varint,1,opt,name=action,proto3,enum=blackjack.v1.blackjack.Turn_TURN_ACTION" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Turn) Reset() {
	*x = Turn{}
	mi := &file_proto_blackjack_v1_blackjack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Turn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Turn) ProtoMessage() {}

func (x *Turn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blackjack_v1_blackjack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Turn.ProtoReflect.Descriptor instead.
func (*Turn) Descriptor() ([]byte, []int) {
	return file_proto_blackjack_v1_blackjack_proto_rawDescGZIP(), []int{1}
}

func (x *Turn) GetAction() Turn_TURN_ACTION {
	if x != nil {
		return x.Action
	}
	return Turn_TURN_ACTION_UNSPECIFIED
}

var File_proto_blackjack_v1_blackjack_proto protoreflect.FileDescriptor

const file_proto_blackjack_v1_blackjack_proto_rawDesc = "" +
	"\n" +
	"\"proto/blackjack/v1/blackjack.proto\x12\x16blackjack.v1.blackjack\x1a\x18proto/deck/v1/deck.proto\"\x8f\x03\n" +
	"\x04Game\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x125\n" +
	"\fplayer_cards\x18\x02 \x03(\v2\x12.deck.v1.deck.CardR\vplayerCards\x12D\n" +
	"\x14visible_dealer_cards\x18\x03 \x03(\v2\x12.deck.v1.deck.CardR\x12visibleDealerCards\x12!\n" +
	"\fplayer_score\x18\x04 \x01(\x05R\vplayerScore\x12!\n" +
	"\fdealer_score\x18\x05 \x01(\x05R\vdealerScore\x12@\n" +
	"\x06status\x18\x06 \x01(\x0e2(.blackjack.v1.blackjack.Game.GAME_STATUSR\x06status\"i\n" +
	"\vGAME_STATUS\x12\x1b\n" +
	"\x17GAME_STATUS_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fGAME_STATUS_WAITING_FOR_PLAYERS\x10\x01\x12\x18\n" +
	"\x14GAME_STATUS_FINISHED\x10\x02\"\xa0\x01\n" +
	"\x04Turn\x12@\n" +
	"\x06action\x18\x01 \x01(\x0e2(.blackjack.v1.blackjack.Turn.TURN_ACTIONR\x06action\"V\n" +
	"\vTURN_ACTION\x12\x1b\n" +
	"\x17TURN_ACTION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTURN_ACTION_HIT\x10\x01\x12\x15\n" +
	"\x11TURN_ACTION_STAND\x10\x02B\xd4\x01\n" +
	"\x1acom.blackjack.v1.blackjackB\x0eBlackjackProtoP\x01Z,github.com/chn555/schemas/proto/blackjack/v1\xa2\x02\x03BVB\xaa\x02\x16Blackjack.V1.Blackjack\xca\x02\x16Blackjack\\V1\\Blackjack\xe2\x02\"Blackjack\\V1\\Blackjack\\GPBMetadata\xea\x02\x18Blackjack::V1::Blackjackb\x06proto3"

var (
	file_proto_blackjack_v1_blackjack_proto_rawDescOnce sync.Once
	file_proto_blackjack_v1_blackjack_proto_rawDescData []byte
)

func file_proto_blackjack_v1_blackjack_proto_rawDescGZIP() []byte {
	file_proto_blackjack_v1_blackjack_proto_rawDescOnce.Do(func() {
		file_proto_blackjack_v1_blackjack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_blackjack_v1_blackjack_proto_rawDesc), len(file_proto_blackjack_v1_blackjack_proto_rawDesc)))
	})
	return file_proto_blackjack_v1_blackjack_proto_rawDescData
}

var file_proto_blackjack_v1_blackjack_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_blackjack_v1_blackjack_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_blackjack_v1_blackjack_proto_goTypes = []any{
	(Game_GAME_STATUS)(0), // 0: blackjack.v1.blackjack.Game.GAME_STATUS
	(Turn_TURN_ACTION)(0), // 1: blackjack.v1.blackjack.Turn.TURN_ACTION
	(*Game)(nil),          // 2: blackjack.v1.blackjack.Game
	(*Turn)(nil),          // 3: blackjack.v1.blackjack.Turn
	(*v1.Card)(nil),       // 4: deck.v1.deck.Card
}
var file_proto_blackjack_v1_blackjack_proto_depIdxs = []int32{
	4, // 0: blackjack.v1.blackjack.Game.player_cards:type_name -> deck.v1.deck.Card
	4, // 1: blackjack.v1.blackjack.Game.visible_dealer_cards:type_name -> deck.v1.deck.Card
	0, // 2: blackjack.v1.blackjack.Game.status:type_name -> blackjack.v1.blackjack.Game.GAME_STATUS
	1, // 3: blackjack.v1.blackjack.Turn.action:type_name -> blackjack.v1.blackjack.Turn.TURN_ACTION
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_blackjack_v1_blackjack_proto_init() }
func file_proto_blackjack_v1_blackjack_proto_init() {
	if File_proto_blackjack_v1_blackjack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_blackjack_v1_blackjack_proto_rawDesc), len(file_proto_blackjack_v1_blackjack_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_blackjack_v1_blackjack_proto_goTypes,
		DependencyIndexes: file_proto_blackjack_v1_blackjack_proto_depIdxs,
		EnumInfos:         file_proto_blackjack_v1_blackjack_proto_enumTypes,
		MessageInfos:      file_proto_blackjack_v1_blackjack_proto_msgTypes,
	}.Build()
	File_proto_blackjack_v1_blackjack_proto = out.File
	file_proto_blackjack_v1_blackjack_proto_goTypes = nil
	file_proto_blackjack_v1_blackjack_proto_depIdxs = nil
}
